### ISSUE TITLE
Having trouble configuring for lerna monorepo

### ISSUE THREAD

**Issue by djErock** [firsttris/vscode-jest-runner#61] opened 2020-01-31 15:25 UTC
When I run test file I get --> Error: Cannot find module 'c:\Users\grosskue\Documents\apps\VCRM\node_modules\jest\bin\jest.js'

Truied adding -->

    "jestrunner.configPath": "/client/jest.config.js",
    "jestrunner.jestPath": "${workspaceRoot}/client/node_modules/jest/bin/jest",
    "jestrunner.debugOptions": {
        "args": [
            "--no-cache"
        ],
        "sourcemaps": "inline",
        "disableOptimisticBPs": true,
     }

Error: Cannot find module 'C:\Program Files\Git\client\node_modules\jest\bin\jest'

I need to set:
 configPath with the rootdir/jest.config.js

and 

jestPath --> configPath with the rootdir/node_modules/jest/bin/jest

for each package and when I right click a file it picks up where I am and set the paths accordingly.

Can this be done?

**Comment by firsttris** [comment] 2020-01-31 15:41
@djErock 

i don't think you need that config. this is normally done automatically.

please check this https://github.com/firsttris/vscode-jest-runner/issues/37 where i once explained 

let me know if this answers your question

**Comment by djErock** [comment] 2020-01-31 15:55
It works if I am inside the package but I am at the root folder of the monorepo. I need to pick up the local jest config for whatever menu I am clicking in from context

**Comment by firsttris** [comment] 2020-01-31 16:16
you would need a config in the root folder. there is no way of jest knowing from which folder it should pick up the config.

what you mean is possible with workspaces in vscode https://code.visualstudio.com/docs/editor/multi-root-workspaces. then my extension would be able to pick the correct config.

but if you use a monorepo with lerna or yarn:

-you either open vscode 2 times
-you use vscode worksapces on top if it
-you can have a jest config in root for both of your projects. and open the monorepo in vscode.

**Comment by djErock** [comment] 2020-01-31 16:20
Right now I have this structure -->

-project folder 
--client folder
--base jest config file
----packages
------project1
-------- jest.config <-- imports base config from client root
------project2
-------- jest.config <-- imports base config from client root
------project3
-------- jest.config <-- imports base config from client root

**Comment by djErock** [comment] 2020-01-31 16:21
jest runner is looking in the project root for node modules/jest.js
I need to configure jest runner to look in the package root instead of wherever I am right clicking for the jest config and the jest file

**Comment by firsttris** [comment] 2020-01-31 16:23
Thats only possible with vscode workspaces. See my previous comment for your options

**Comment by djErock** [comment] 2020-01-31 16:34
I need to leave the workspace config alone. Is there no way to add a rootPath or cwd config var to the context so that jest runner will start from that point?

**Comment by firsttris** [comment] 2020-01-31 16:48
think about it. how should this work? those are just folders to vscode and jest. how should vscode or jest know when to use which of your 3 projects?..

this would only be possible when you would write you own config and jest resolver..

**Comment by djErock** [comment] 2020-01-31 16:59
This is going to be difficult/borderline unusable for anyone in a mono repo structure.

**Comment by firsttris** [comment] 2020-01-31 17:06
im using mono repo myself and it works very well. you are the first who complains, and the addon has 41k install.

i think you have a misunderstanding on your side. the issue is not my addon.
go to your root folder and execute jest. does it work ? no - because jest can't find the config.
my addon is just executing jest. that's it.

i already pointed you at different possible solutions for your setup.

i will close this issue at this point. since i don't see any possible way to fix this.

**Closed by firsttris** 2020-01-31 17:06 UTC

**Comment by djErock** [comment] 2020-01-31 17:22
Let me try this one more time:

- project folder <-- jestrunner looks here
-- client folder <-- I need jestrunner to look here
---- jest config file
-- server folder
-- DB folder

In project folder I added this to vs code settings.json

{
    "jestrunner.configPath": "/client",
    "jestrunner.jestPath": "/client",
    "jestrunner.debugOptions": {
        "args": [
            "--no-cache"
        ],
        "sourcemaps": "inline",
        "disableOptimisticBPs": true,
    }
}

I get this when running "Run Jest File" command in context -->

$ node "/client" "c:/Users/grosskue/Documents/apps/VCRM/client/packages/vcrmcomponents/src/components/common/modals/common/VcrmModalDataTable.spec.js" -c "c:/Users/grosskue/Documents/apps/V
CRM/client"
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\client'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by firsttris** [comment] 2020-01-31 17:43
no really i have no idea how you can get it working like you want it.

if all of your projects are javascript projects, why can't you have an additional global jest config in root? just for this purpose
you could also install jest globally and set it to jestrunner.jestPath (full absolut path)

would that be a solution?

**Comment by firsttris** [comment] 2020-01-31 17:44
you could also install jest in root (just for this purpose).

acutally that usually how people would configure the project. in your situation.
