### ISSUE TITLE
Limit to js and ts files

### ISSUE THREAD

**Issue by domoritz** [firsttris/vscode-jest-runner#33] opened 2019-08-01 20:30 UTC
Right now, the commands also show up in Python files for me, which I find very distracting.

**Comment by firsttris** [comment] 2019-08-16 08:11
want this as well...

didn't find any way to do it, thats way i also put in under Known-Issues in the Readme
https://github.com/firsttris/vscode-jest-runner#known-issues

**Comment by domoritz** [comment] 2019-08-17 08:09
It looks like this could help here: https://stackoverflow.com/a/43958797/214950

**Comment by firsttris** [comment] 2019-08-17 15:37
I think the problem is the actual context-menu command will be defined in the package.json
https://github.com/firsttris/vscode-jest-runner/blob/master/package.json#L75

An in the answer from your stackoverflow link he states 
> I'm afraid this is impossible for now.

With the code from stackoverflow we could disable all the logic behind this command, but the command would still show up in the context menu.

And i think that's what we want to avoid.

For some days there was a PR who puts the context-menu commands in another group, so the wont at least not show up on top.

**Comment by domoritz** [comment] 2019-08-17 19:31
Thanks for explaining the problem to me. I wonder how the python extension for vscode handles this. A quick look through the codebase didn't reveal their secret to me.

**Comment by firsttris** [comment] 2019-12-13 20:31
closing this, since it seems implossible for now. please re-open if there is a solution.

**Closed by firsttris** 2019-12-13 20:31 UTC
Labels: enhancement
