### ISSUE TITLE
Yarn PnP support doesnt work - Jest location cannot be resolved properly

### ISSUE THREAD

**Issue by karol-pawlowski** [firsttris/vscode-jest-runner#110] opened 2020-10-15 20:20 UTC
Hi Guys,

Unfortunately, I'm unable to use vscode-jest-runner for debugging purposes. Environment details:

Version: 1.49.3 (system setup)
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:57:01.595Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

vscode-jest-runner version: v0.4.27

When switching on the yarn PnP flag "jestrunner.enableYarnPnpSupport" extensions still tries to resolve jest location under "node_modules". 

Rejected candidate: c:\***\workspace\node_modules\jest\bin\jest.js
Rejected candidate: c:\***\workspace\node_modules\jest\bin\jest.js.js
Rejected candidate: c:\***\workspace\node_modules\jest\bin\jest.js.json
Rejected candidate: c:\***\workspace\node_modules\jest\bin\jest.js.node 

Switching on the flag "jestrunner.detectYarnPnpJestBin" doesn't work as well.
The same paths are used for jest resolution without even considering the .yarn/cache/*.

The only way to make the extension partially working is to override the command by: 
"jestrunner.jestCommand": "yarn run jest ${fileBasenameNoExtension} --no-cache --no-watch --runInBand",

but the problem is that it's triggered only for test run but not for debug.
Would be glad for look at it.

Kind Regards
Karol Pawlowski

**Comment by firsttris** [comment] 2020-10-16 18:28
hey @karol1990 thx for this detailed report.
the feature was implemented by @alexkuc with https://github.com/firsttris/vscode-jest-runner/pull/103
he mentioned that he doesn't know how to invoke yarn with pnp feature enabled on windows.

https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunnerConfig.ts#L37
my understanding is if jestrunner.detectYarnPnpJestBin is true it should return yarnPnpJestBinPath() which is 'yarn bin jest'

is this correct for windows?

regards
Tristan

**Comment by karol1990** [comment] 2020-10-16 21:54
Hey @firsttris, the path that gets generated with flag "jestrunner.detectYarnPnpJestBin" is following:
Rejected candidate: C:\***\workspace\`yarn bin jest`
Rejected candidate: C:\***\workspace\`yarn bin jest`.js
Rejected candidate: C:\***\workspace\`yarn bin jest`.json
Rejected candidate: C:\***\workspace\`yarn bin jest`.node

what means "yarn bin jest" doesn't get evaluated but gets combined with workspace directory.
Looking at the code I can't locate the place that `yarn bin jest` would be evaluated.
Worth to mention that 'yarn bin jest' returns the absolute path to jest location in the yarn cache:
C:\***\workspace\.yarn\cache\**jest-npm-26.4.2-65f7183830-e577e48631.zip**\node_modules\jest\bin\jest.js
so you won't be able to invoke it from within the command. "Yarn unplug jest" would have to be called first but not sure if this is a good idea.

What about giving users the possibility to override debug command?

regards
Karol

**Comment by alexkuc** [comment] 2020-10-16 22:17
@karol1990 @firsttris 

From my recollection of how this feature works.

- `isYarnPnpSupportEnabled`: executes `node --require .pnp.js` ([reference](https://stackoverflow.com/questions/60059687/how-do-i-use-yarns-pnp-js-file))
- `detectYarnPnpJestBin`: detects path to Jest bin by running `yarn bin jest` as shell code; as noted in GUI, it is currently supported *only* on Linux/Unix systems

So if you are on Windows, you would need to manually specify path to binary in one of the VSCode Jest Runner plugin settings.

**Comment by alexkuc** [comment] 2020-10-16 22:21
@karol1990 

> Looking at the code I can't locate the place that yarn bin jest would be evaluated.

There are actually back ticks to execute the code in shell ([source](https://github.com/firsttris/vscode-jest-runner/pull/103/files#diff-2629deea182d3750760ab47df1b82a9e2f95761cefd984f60a44de01c3ac5709R102)). Normally, the execution should happen in the root of the repository i.e. folder where `.pnp.js` is located

**Comment by alexkuc** [comment] 2020-10-16 22:26
@karol1990 

> so you won't be able to invoke it from within the command.

You are not meant to invoke `jest.js` directly but rather require it via `node --require <absolute_path_to_jest_bin>`.

While on Linux/Unix systems, it is fairly straight forward to execute a sub-shell command to determine the path dynamically, I am not sure how the workflow works on Windows. I am referring to different flavors of shells and how they are configured. For example, you could invoke `node.exe` via cmd or via P$ or via miniGW. All of these would have different implications hence my PR included support only for areas I knew better.

Ps. I have used back ticks instead of better format `$(…)` due to me not being able to avoid the dollar sign being escaped.

**Comment by karol1990** [comment] 2020-10-19 11:10
Hey @alexkuc, 
> So if you are on Windows, you would need to manually specify path to binary in one of the VSCode Jest Runner plugin settings.

I've tried this way by overriding `jestrunner.jestPath` settings. The problem is that you would have to unplug the package what is I don't want to do. Wouldn't be easier to give programmer option to override both run and debug commands in such circumstances ?

**Comment by alexkuc** [comment] 2020-10-19 12:51
@karol1990 

> The problem is that you would have to unplug the package what is I don't want to do.

I am not sure if I follow but why would you need to unplug the binary? You would manually run [yarn bin](https://yarnpkg.com/cli/bin) and specify it as `jestrunner.jestPath`. If you would navigate to the path given by Yarn 2 Pnp, you would notice that it is pointing to the inside of the `.zip` file. E.g. `.yarn/cache/jest-cli-npm-26.4.2-046301e896-1dc23b584d.zip/node_modules/jest-cli/bin/jest.js`, which is why it is necessary to require `.pnp.js` otherwise Yarn 2 Pnp module would not load properly (vanilla Node does not support loading modules for archives such as zip files).

> Wouldn't be easier to give programmer option to override both run and debug commands in such circumstances ?

Technically, that would be an entirely different feature and you would still need the necessary knowledge to load Yarn 2 Pnp. This Yarn 2 Pnp is like a preset of a configuration.

**Comment by karol1990** [comment] 2020-10-19 18:17
Hey @alexkuc, I'm not sure why I've been failing before to use the relative path of yarn location. It worked well now and will go with jestrunner.jestpath setting. Thanks

**Comment by alexkuc** [comment] 2020-10-19 18:21
@karol1990 

I think in some circumstances you need to use absolute path. Glad you got it working!

**Comment by karol1990** [comment] 2020-10-19 19:17
@alexkuc, unfortunately, an absolute path is not considered as the setting is set in the workspace file and shared with other developers. I see that if the solution was opened via workspace file, even if I change the current directory, debug/run actions bring back the workspace location and set it as current and so it makes the relative path working well.

**Comment by firsttris** [comment] 2020-11-17 18:32
closing the issue here, 

thx for your help @alexkuc

**Closed by firsttris** 2020-11-17 18:32 UTC
Labels: bug
